version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint 
    - gocritic
    - misspell
    - revive
  exclusions:
    rules:
      - linters: [revive]
        text: "unused-parameter"
      - linters: [revive]
        text: "^exported:"
      - linters: [revive]
        text: "^package-comments:"
      - linters: [revive]
        text: "^blank-imports:"

formatters:
  enable:
    - gofmt
    - goimports
