version: "2"

linters:
  default: standard
  enable:
    - bodyclose
    - errorlint 
    - gocritic
    - misspell
    - revive
  exclusions:
    rules:
      - linters: [revive]
        text: "unused-parameter"

formatters:
  enable:
    - gofmt
    - goimports
